api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "volume-logic"
type = "function"
uid = "9933db48-0ac0-b410-942b-8ced45396fec71d380a3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart_delivery_options_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/volume-logic.wasm"
  watch = [ "src/**/*.rs" ]
